# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Text Input"
  description:
  icon: create
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name_and_id: ""
  label: ""
  required: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Text
  name_and_id: name_and_ID

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
