collections_config:
  pages:
    schemas:
      default:
        path: schemas/page.md
    _enabled_editors:
      - visual
  speakers:
    schemas:
      default:
        path: schemas/speaker.md
    _enabled_editors:
      - content
  talks:
    schemas:
      default:
        path: schemas/talk.md
    _enabled_editors:
      - content

_inputs:
  _uuid:
    instance_value: UUID
    hidden: true
  speakers:
    type: multiselect
    options:
      values: collections.speakers
      value_key: _uuid
      text_key: name