baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'HugoConf 2023'

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'