# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Checkbox-group"
  description:
  icon: done_all
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  checkboxes: [bookshop:generic/form/checkbox-input]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  checkboxes: 
    - bookshop:generic/form/checkbox-input
    - bookshop:generic/form/checkbox-input
    - bookshop:generic/form/checkbox-input


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
