# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Email-input"
  description:
  icon: mail_outline
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name_and_id: ""
  label: ""
  required: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Email
  name_and_id: name_and_ID

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  name_and_id:
    comment: Provides a unique identifier for the input