# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Email-input"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _name: UUID
  label: ""
  required: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Email

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: