# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hexagon-block"
  description:
  icon: rounded_corner
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  hexagon_color: pink
  title:
  content:
  _text_alignment: left
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  hexagon_color: pink
  title: I am a title
  content: <p>Doggo ipsum such treat floofs doge. Maximum borkdrive borkf smol borking doggo with a long snoot for pats clouds waggy wags, what a nice floof snoot. Heckin adorable doggo pupper tungg, boof what a nice floof yapper wow very biscit, length boy bork. He made many woofs borkdrive snoot heckin, doing me a frighten. Fat boi very good spot maximum borkdrive wow such tempt aqua doggo, you are doin </p>

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content:
    type: html
  hexagon_color:
    type: select
    options:
      values:
        - green
        - pink
        - yellow
