# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Simple Form"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  email: bookshop:generic/input
  name: bookshop:generic/input
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  email:
    type: email
    name: email
    label: Email address
    required: true

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
