# Metadata about this component, to be used in the CMS
spec:
  structures:
    - modal_blocks
  label: "Form"
  description:
  icon: dynamic_form
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _instancevalue: UUID
  form_submission_type: email/cloudcannon
  success_page: ""
  mailchimp_submission_action: ""
  inputs: [bookshop:structure:form_blocks]
  tandc_checkbox: bookshop:generic/form/checkbox-input
  submit_button: bookshop:generic/button
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  inputs:
    - bookshop:structure:form_blocks
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  form_submission_type:
    comment: This option will provide the type of submission that will be targeted. 
    type: select
    options:
      values:
      - email/cloudcannon
      - mailchimp
  mailchimp_submission_action: 
    comment: Is only required if mailchimp has been selected as your submission_type example - https://componay.us12.list-manage.com/subscribe?u=c2asfj8ec0sdfjsadlfe3f&id=88786d434e
  _instancevalue:
    instance_value: UUID
  success_page:
    type: url
    comment: Is only required if email/cloudcannon has been selected as your submission_type. This will be the page the user will be taken on successful submission.
