# Metadata about this component, to be used in the CMS
[spec]
structures = []
label = "Event date"
description = ""
icon = "date_range"
tags = []

# Defines the structure of this component, as well as the default values
[blueprint]
date = ""
# Overrides any fields in the blueprint when viewing this component in the component browser
[preview]
date = "I am a date/event subtitle"

# Any extra CloudCannon inputs configuration to apply to the blueprint
[_inputs]
[_inputs.date]
type = "text"
