# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Speaker List
  description: Section to display list of speakers
  icon: emoji_events
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
