# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Radio-input"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  input-name: "" #: *Required
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Hello I am a radio-button!"
  input_name: "input" 

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
