# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Radiobutton-group"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Hello World!"
  radiobuttons: [bookshop:generic/form/radio-input]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Hello I am a radiobutton group!"
  radiobuttons:
    - bookshop:generic/form/radio-input
    - bookshop:generic/form/radio-input
    - bookshop:generic/form/radio-input
    - bookshop:generic/form/radio-input
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
