# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Video-section"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  video: bookshop:simple/video
  button: bookshop:generic/button
  notice_message: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  notice_message: "This is a notice message"
  button:
    label: I am a button
    view_label_icon: false
    border_color: border-white

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  notice_message:
    type: html
