# Metadata about this component, to be used in the CMS
spec:
  structures:
    - form_blocks
  label: "Conditional-input"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _name: UUID
  label: ""
  checked: false
  inputs: [bookshop:structure:form_blocks]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "I am a conditional checkbox"
  inputs: 
    - bookshop:structure:form_blocks
    - bookshop:structure:form_blocks

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  _name:
    instance_value: UUID