# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Schedule
  description: Section to display speakers and talks
  icon: emoji_events
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  talks: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "9 June 2022"
  talks:
    - time: "7:00 am - 7:05 am PST"

