# Metadata about this component, to be used in the CMS
[spec]
structures = []
label = 'Button'
description = 'button'
icon = 'smart_button'
tags = []

# Defines the structure of this component, as well as the default values
[blueprint]
label = ""
view_label_icon = "true" #: Adds icon to button
border_color = ["border-blue","border-pink","border-white"]

# Overrides any fields in the blueprint when viewing this component in the component browser
[preview]
label = "I am a button"
border_color = ["border-blue","border-pink","border-white"]


# Any extra CloudCannon inputs configuration to apply to the blueprint
[_inputs]
[_inputs.view_label_icon]
type = "switch"
[_inputs.border_color]
type = "select"