# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Button
  description: button
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  id: ""
  view_label_icon: true
  border_color: border-blue
  add_modal: false
  open_modal: false
  modal: bookshop:simple/modal

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "I am a label"
  view_label_icon: true
  border_color: border-blue

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    type: text
  view_label_icon:
    type: switch
  border_color:
    type: select
    options:
      values:
        - border-blue
        - border-pink
        - border-white
  open_modal:
    hidden: "add_modal"
  modal:
    hidden: "add_modal"